# ----------------------------------------------------------------------------
# Copyright 2023 The Netty Project
#
# The Netty Project licenses this file to you under the Apache License,
# version 2.0 (the "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at:
#
#   https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
# ----------------------------------------------------------------------------
name: thread dump jvms
description: Triggers a thread dump for all running JVMs
runs:
  using: composite
  steps:
    - run: |
        if [[ "$OSTYPE" == "linux-gnu"* ]] && command -v sudo &> /dev/null; then
          # use jattach so that Java processes in docker containers are also covered
          curl -s -L -o /tmp/jattach https://github.com/apangin/jattach/releases/download/v2.1/jattach
          chmod +x /tmp/jattach
          for java_pid in $(sudo pgrep java); do
            echo "----------------------- pid $java_pid -----------------------"
            echo "command line: $(sudo cat /proc/$java_pid/cmdline | xargs -0 echo)"
            sudo /tmp/jattach $java_pid jcmd "Thread.print -l"
            sudo /tmp/jattach $java_pid jcmd GC.heap_info
          done
        else
          while read -a line; do
            java_pid=${line[0]}
            echo "----------------------- pid $java_pid -----------------------"
            echo "command line: ${line[*]:1}"
            jcmd $java_pid Thread.print -l
            jcmd $java_pid GC.heap_info
          done <<< $(jps -v -J-XX:+PerfDisableSharedMem)
        fi
        exit 0
      shell: bash